### PR TITLE
[WIP] OSI networking primer

### PR DESCRIPTION
**Pull request by lucperkins**
cc @edwarnicke @fkautz

This is definitely a WIP but I'm honestly not sure how useful it is, so I thought I'd put this up here to see if you two think something like this should be provided in the NSM docs or if it'd be best to delegate to exterrnal sources. If the former, let me know and I'll happily keep plugging away.

Relevant doc: https://deploy-preview-106--nsm.netlify.com/docs/concepts/l2-l3/

### CODE REVIEW

**Comment by edwarnicke** [comment]
@lucperkins This is an interesting start... will think about it a bit :)

**Comment by edwarnicke** [comment]
@lucperkins I was chatting with @dtornow today... and he has an interesting way of looking at things in terms of 'Connectivity' instead of OSI model layers... thought you two should talk and collaborate :)

**Comment by lucperkins** [comment]
@edwarnicke Okay, happy to chat. I do think, however, that *some* explanation of the OSI layers should be included given how prominently NSM touts itself as an L2/L3 system.

**Comment by dtornow** [comment]
@lucperkins Hey Luc, good to hear from you again (I'm still raving about that hot pot place). Are you available for a call sometimes to kick things off?

**Comment by lucperkins** [comment]
@dtornow @edwarnicke Oh *that* Dominik! :smile: :100: Yes, feel free to hit me up on Slack and we'll talk.

I'll keep this PR open for now as a vessel for future work.

**Pull request closed without merging**
