### PR TITLE
Bump: Add release notes for v1.4.0

### PR DESCRIPTION
**Pull request by denis-tingaikin**
Signed-off-by: Denis Tingaikin <denis.tingajkin@xored.com>

### CODE REVIEW

**Comment by edwarnicke** [comment]
LGTM - lets review at the community call tomorrow

**Comment by denis-tingaikin** [comment]
@edwarnicke Sure, its good idea!

**Comment by denis-tingaikin** [comment]
Preview: https://deploy-preview-223--nsm.netlify.app/

**Comment by fkautz** [comment]
For go we should clarify if we are only compiling with go 1.18 or if we have an api compatibility requirement of 1.18+.

**Pull request merged**
